options:
  lineNumbers: true
  spellcheck: false
  askImageFilename: true
  overwriteImages: false
  imagePrefix: pasted-99999
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: false
